### ISSUE TITLE
determinism/roll back

### ISSUE THREAD

**Issue by logixworx** [adamreichold/rs-ecs#33]
"It is not thread-safe as the execution of single-threaded simulations is trivially deterministic"

does this mean rs-ecs is deterministic and suitable for rollback netcode with serialization (serde) ?

**Comment by adamreichold** [comment]
> does this mean rs-ecs is deterministic and suitable for rollback netcode with serialization (serde) ?

If your systems themselves are deterministic, then a simulation built using rs-ecs is deterministic in the sense that the ECS will produce exactly the same query results in the same order for every execution. 

I am not sure whether this property is really related to "rollback netcode" though: If you rollback the world state and give it the same inputs, this should always result in the same updated state. But if you use different inputs, then the ECS itself will _not_ ensure that the resulting state is somehow correlated even if your systems themselves are well-behaved. For example, if a changed input leads to a different order when inserting and/or removing components, the resulting ECS state will yield different results for subsequent queries.

On the other hand, if all nodes (after rollback if necessary) apply exactly the same modifying operations (adding/removing entities and/or components) on their `World` instances in the same order, then they will get exactly the same query results. Meaning that if the inputs fully determine what your systems do to the `World`, then there will be no interference from any hidden state like randomized hash functions or local state like memory allocation addresses.

I am admittedly not really sure for what property your are looking exactly. Does this answer your question? If not, could you be more specific which kind of determinism you need from your ECS to apply "rollback netcode"?

**Comment by logixworx** [comment]
Your response answered my question precisely. Thanks!     

 What about serialization, what would I have to do to serialize the entire world state with serde ?

**Comment by adamreichold** [comment]
> What about serialization, what would I have to do to serialize the entire world state with serde ?

Now this is a difficult one. Note that if you want to serialize a `World`, deserialize it later, continue the simulation and expect the same results as if you had continued with the serialization-deserialization step in between, you would need to include the order of the archetypes and the order of the entities in the archetypes in your serialization format.

At the moment, these internals are not exposed at all and I don't think you can just query all entities/components to serialize them and then just recreate them using methods like `World::alloc` and `World::insert` as this would yield a different order of archetypes and entities within the archetypes.

But doing so generically, e.g. something like `impl Serialize for World`, is also difficult as we cannot generally assume that all components implement `Serialize` themselves. And even if we did require that, we would need to store those vtables somewhere as we do not "know" the types generically.

Finally, do you strictly need serialization of the `World` state? I suspect you need that for the rollback part? If that is the case, wouldn't something simpler like being able to clone a `World` instance in memory suffice? So for example, cloning your world into a snapshot and later replacing your updated world with that snapshots ("rolling back") if inputs were predicted incorrectly?

Implementing this would be straight forward if it could be an `unsafe` operation that could assume that all components are `Copy`. If you store owning components like `Vec` or `String`, then this would need to integrate with `Clone` which I would need to like into but seems plausible still (basically store an optional function pointer per component type for cloning a single component value).

**Comment by adamreichold** [comment]
Hhhmmm, I do fear both automatic serialization and cloning would need specialization... Using stable Rust, only unsafe automatic cloning assuming purely `Copy` components seems achievable.

**Comment by mlange-42** [comment]
> Now this is a difficult one. Note that if you want to serialize a World, deserialize it later, continue the simulation and expect the same results as if you had continued with the serialization-deserialization step in between, you would need to include the order of the archetypes and the order of the entities in the archetypes in your serialization format.

Wouldn't the same order be established by adding entities in the order (and archetype order) they had in the serialized world?
Create entities of the first archetype -> first archetype is created, and entities have the correct order. -> proceed with second archetype...

Just entity IDs would differ, or would need to be generated explicitly.

**Comment by logixworx** [comment]
"Finally, do you strictly need serialization of the World state?"  Yes, the latter is what i desire. Some ECS's (brood, legion) have this feature & use serde for serialization

**Comment by adamreichold** [comment]
> > Now this is a difficult one. Note that if you want to serialize a World, deserialize it later, continue the simulation and expect the same results as if you had continued with the serialization-deserialization step in between, you would need to include the order of the archetypes and the order of the entities in the archetypes in your serialization format.
> 
> Wouldn't the same order be established by adding entities in the order (and archetype order) they had in the serialized world? Create entities of the first archetype -> first archetype is created, and entities have the correct order. -> proceed with second archetype...
> 
> Just entity IDs would differ, or would need to be generated explicitly.

Yes, that could be one way to implement a deserialization method. The is point is that additional API and a careful implementation is required. And a serialization method (and format) which respects this ordering. Meaning it has bad ergonomics to let the user open code and this and it does place additional constrains on the serialization format as well which cannot be checked by the code here.

**Comment by adamreichold** [comment]
> "Finally, do you strictly need serialization of the World state?" Yes, the latter is what i desire. Some ECS's (brood, legion) have this feature & use serde for serialization

They do this by requiring the user to enumerate all component types to collect up their `Serialize` impls and provide an externally visible and unique type name. Would these ergonomics be sufficient from your point of view? Personally, I find that much too fragile but I guess it could be implemented.

**Comment by adamreichold** [comment]
Out of curiosity, could you explain why serializing the inputs and snapshotting the world in memory is not sufficient for your use case resp. for rollback netcode in general?

**Comment by adamreichold** [comment]
While I did some experimentation on it, c.f. #35, I do not think I will add serializatzion support using Serde to this crate. The manual type registration using manually assigned keys is error prone and I do not see how deserialization could be made safe at all, as the various implicit invariants between the different indices could easily lead to type confusion bugs if a superficially correct but subtly invalid serialization is turned into a `World`. Additionally, the requirement to go through [`erased-serde`](https://crates.io/crates/erased-serde) significantly reduces the efficiency of the approach.

I will continue to investigate snapshotting/cloning a `World` in way that is compatible with stable Rust, i.e. using a manual type registry but at least one with a fully safe interface. I think this is more fruitful as it could eventually just become `impl Clone for World` when specialization is stabilized and it should be much more efficient than serialization for the rollback use case. Finally, I still think that snapshotting in memory and serialization of inputs is sufficient to implement rollback netcode and similar techniques.
